### ISSUE TITLE
Permit whitelisting specific hosts

### ISSUE THREAD

**Issue by danielbachhuber** [humanmade/node-tachyon#11]
As a Tachyon user, it would be helpful if I could whitelist specific image domains, to only permit resizing / hosting images from those domains.

**Comment by joehoyle** [comment]
I think this would be better implemented at the CDN / proxy level than in `tachyon` it's self. Keeping Tachyon single-task, it's best used put behind some level of caching / reverse proxy. Starting it in node is just passed a port, similar to how running any other Express server would be.

**Comment by danielbachhuber** [comment]
Closing because of #12
