### ISSUE TITLE
Support for resizing arbitrary images on the web

### ISSUE THREAD

**Issue by danielbachhuber** [humanmade/node-tachyon#12]
Just like its predecessor, it would be cool if I could use Tachyon to resize arbitrary images on the web (instead of being closely coupled to AWS / S3)

From #11

**Comment by rmccue** [comment]
IMO, I'd rather this be a separate project than in Tachyon. Keeping Tachyon as image-processing-for-a-bucket keeps the scope nice and tight. Supporting arbitrary images seems like a separate task; you could build a small service on top of Tachyon that downloads the image to your bucket first, then passes that to Tachyon.

@joehoyle?

**Comment by joehoyle** [comment]
I'd agree, I'm going to close this out as it's conceptual out of scope for this project.
