### ISSUE TITLE
Support for rotation

### ISSUE THREAD

**Issue by roborourke** [humanmade/node-tachyon#13]
Now that Tachyon will be used outside of the HM sphere there are requirements from one client project where we'll need to provide a full thumbnail editor, this includes the cropping from #8 and also rotation.

It's really simple to add with minimal overhead too so I can't think of a reason not to support it.

**Comment by joehoyle** [comment]
Hmm, can't this be done in WordPress ala the normal editor?

**Comment by roborourke** [comment]
@joehoyle yeah but not a great experience, the idea being we'd just deliver a request for the original image and append the size, crop and rotation data in the query string. Will put this on hold though, rotation is kinda moot these days so will push back with the client, see if they really need it. #8 definitely needed though

**Comment by joehoyle** [comment]
Hmm ok - is this support for the device rotation image meta data, or do they specifically want an image rotated sideways for some specific image location?
