### ISSUE TITLE
Support for crop location

### ISSUE THREAD

**Issue by roborourke** [humanmade/node-tachyon#4]
Some plugins generate an asymmetrically centred cropped image. It'd be good to have this option eg a crop x & y param to indicate the point of interest on the image. Adding these values to the tachyon URLs can be done on plugin by plugin basis.

eg. `tchyn.io/path/to/image.jpg?width=200&height=400&crop=1&cropxy=600,100`

**Comment by joehoyle** [comment]
@roborourke this is now in production on `eu-central-1` (so UI), let me know if looks good. I tried it out with say http://eu-central-1.tchyn.io/unitedbloggers-sweden-production/uploads/sites/21/2016/08/IMG_1204.jpg?crop=0,0,50,50&w=100

**Comment by roborourke** [comment]
Cheers @joehoyle - yeah seems to work well. Using the develop branch on IM
at the moment.
